# Income Age 2010

In [1]:
# Dependencies
import requests
import pandas as pd
from census import Census
import json

In [2]:
# Import U.S. Census API Key
from config import census_key

# Create an instance of the Census library
c = Census(
    census_key,
    year = 2010
)

In [3]:
# Run Census Search to retrieve data on all zip codes (2013 ACS5 Census)
census_data = c.acs5.get(
    (
        "NAME",
        "B19001_001E",
        "B19037_002E",
        "B19037_019E",
        "B19037_036E",
        "B19037_053E"
    ),
    {'for': 'state:*'}
)

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column renaming
census_pd = census_pd.rename(
    columns = {
        "B19001_001E": "Household Income Total",
        "B19037_002E": "Household Income Under 25 years",
        "B19037_019E": "Household Income 25 to 44 years",
        "B19037_036E": "Household Income 45 to 64 years",
        "B19037_053E": "Household Income 65 years and over",
        "NAME": "Name"
    }
)

# Add a Poverty Rate column (Poverty Count / Population)
#census_pd["Poverty Rate"] = 100 * census_pd["Poverty Count"].astype(int) / census_pd["Population"].astype(int)

# Configure the final DataFrame
census_pd = census_pd[
    [
        "Name",
        "Household Income Total",
        "Household Income Under 25 years",
        "Household Income 25 to 44 years",
        "Household Income 45 to 64 years",
        "Household Income 65 years and over"
    ]
]

# Display DataFrame length and sample data
print(f"Number of rows in the DataFrame: {len(census_pd)}")
census_pd

Number of rows in the DataFrame: 52

,Name,Household Income Total,Household Income Under 25 years,Household Income 25 to 44 years,Household Income 45 to 64 years,Household Income 65 years and over
0,Alabama,1821210.0,92105.0,609345.0,709942.0,409818.0
1,Alaska,248248.0,16382.0,92556.0,108542.0,30768.0
2,Arizona,2326468.0,130657.0,829584.0,854117.0,512110.0
3,Arkansas,1117154.0,65996.0,374701.0,417962.0,258495.0
4,California,12392852.0,508953.0,4672455.0,4841018.0,2370426.0
5,Colorado,1918959.0,119242.0,728412.0,747669.0,323636.0
6,Connecticut,1359218.0,41892.0,455558.0,559980.0,301788.0
7,Delaware,331639.0,13019.0,111803.0,131624.0,75193.0
8,District of Columbia,257317.0,15794.0,108897.0,85744.0,46882.0
9,Florida,7152844.0,289746.0,2256737.0,2711444.0,1894917.0
10,Georgia,3468704.0,171785.0,1368072.0,1330391.0,598456.0
11,Hawaii,442267.0,17374.0,139590.0,182596.0,102707.0
12,Idaho,570283.0,41290.0,201284.0,212066.0,115643.0
13,Illinois,4769951.0,200238.0,1746379.0,1833079.0,990255.0
14,Indiana,2465402.0,129740.0,865996.0,952400.0,517266.0
15,Iowa,1215954.0,78703.0,398590.0,454248.0,284413.0
16,Kansas,1101672.0,74833.0,377032.0,415079.0,234728.0
17,Kentucky,1676708.0,83556.0,579380.0,655251.0,358521.0
18,Louisiana,1641165.0,87979.0,564340.0,650224.0,338622.0
19,Maine,551125.0,21553.0,169152.0,231721.0,128699.0
20,Maryland,2121047.0,73599.0,762975.0,868081.0,416392.0
21,Massachusetts,2512552.0,89028.0,870971.0,1004741.0,547812.0
22,Michigan,3843997.0,168012.0,1281120.0,1548896.0,845969.0
23,Minnesota,2085917.0,114602.0,746985.0,805074.0,419256.0
24,Mississippi,1081052.0,49724.0,369744.0,423930.0,237654.0
25,Missouri,2349955.0,130801.0,801582.0,899650.0,517922.0
26,Montana,401328.0,26515.0,121166.0,162540.0,91107.0
27,Nebraska,711771.0,47686.0,244285.0,265404.0,154396.0
28,Nevada,979621.0,48510.0,374776.0,373667.0,182668.0
29,New Hampshire,513804.0,18388.0,169587.0,222297.0,103532.0
30,New Jersey,3176069.0,70799.0,1106623.0,1299422.0,699225.0
31,New Mexico,756112.0,42066.0,245666.0,304306.0,164074.0
32,New York,7205740.0,244842.0,2519722.0,2869471.0,1571705.0
33,North Carolina,3626179.0,191012.0,1312779.0,1382800.0,739588.0
34,North Dakota,276642.0,26257.0,88410.0,100707.0,61268.0
35,Ohio,4552270.0,211190.0,1533106.0,1798561.0,1009413.0
36,Oklahoma,1421705.0,91251.0,479971.0,536879.0,313604.0
37,Oregon,1499267.0,82593.0,512772.0,582404.0,321498.0
38,Pennsylvania,4940581.0,187873.0,1572279.0,1972586.0,1207843.0
39,Rhode Island,410305.0,15792.0,136737.0,165555.0,92221.0
40,South Carolina,1741994.0,86598.0,592653.0,684941.0,377802.0
41,South Dakota,315468.0,21110.0,102359.0,119617.0,72382.0
42,Tennessee,2443475.0,124595.0,855913.0,944725.0,518242.0
43,Texas,8539206.0,498205.0,3351589.0,3191586.0,1497826.0
44,Utah,859158.0,66268.0,356734.0,290893.0,145263.0
45,Vermont,256612.0,11540.0,80527.0,109544.0,55001.0
46,Virginia,2974481.0,135208.0,1079668.0,1181625.0,577980.0
47,Washington,2577375.0,139270.0,935670.0,1011813.0,490622.0
48,West Virginia,740874.0,33291.0,219893.0,297632.0,190058.0
49,Wisconsin,2274611.0,134772.0,775987.0,882090.0,481762.0
50,Wyoming,217688.0,15709.0,71478.0,88585.0,41916.0
51,Puerto Rico,1227039.0,31326.0,385482.0,487812.0,322419.0