# Income Bracket 2021

In [2]:
# Dependencies
import requests
import pandas as pd
from census import Census
import json

In [3]:
# Import U.S. Census API Key
from config import census_key

# Create an instance of the Census library
c = Census(
    census_key,
    year = 2021
)

In [5]:
# Run Census Search to retrieve data on all states (2021 ACS5 Census)
census_data = c.acs5.get(
    (
        "NAME",
        "B19001_001E",
        "B19001_002E",
        "B19001_003E",
        "B19001_004E",
        "B19001_005E",
        "B19001_006E",
        "B19001_007E",
        "B19001_008E",
        "B19001_009E",
        "B19001_010E",
        "B19001_011E",
        "B19001_012E",
        "B19001_013E",
        "B19001_014E",
        "B19001_015E",
        "B19001_016E",
        "B19001_017E"
    ),
    {'for': 'state:*'}
)

# Convert to DataFrame
census_pd = pd.DataFrame(census_data)

# Column renaming
census_pd = census_pd.rename(
    columns = {
        "B19001_001E": "Household Income Total",
        "B19001_002E": "Household Income Less than 10,000",
        "B19001_003E": "Household Income 10,000 to 14,999",
        "B19001_004E": "Household Income 15,000 to 19,999",
        "B19001_005E": "Household Income 20,000 to 24,999",
        "B19001_006E": "Household Income 25,000 to 29,999",
        "B19001_007E": "Household Income 30,000 to 34,999",
        "B19001_008E": "Household Income 35,000 to 39,999",
        "B19001_009E": "Household Income 40,000 to 44,999",
        "B19001_010E": "Household Income 45,000 to 49,999",
        "B19001_011E": "Household Income 50,000 to 59,999",
        "B19001_012E": "Household Income 60,000 to 74,999",
        "B19001_013E": "Household Income 75,000 to 99,999",
        "B19001_014E": "Household Income 100,000 to 124,999",
        "B19001_015E": "Household Income 125,000 to 149,999",
        "B19001_016E": "Household Income 150,000 to 199,999",
        "B19001_017E": "Household Income 200,000 or more",
        "NAME": "Name"
    }
)

# Combine two Income Brackets to one column column
census_pd["Household Income 10,000 to 19,999"] = (census_pd["Household Income 10,000 to 14,999"] + census_pd["Household Income 15,000 to 19,999"]) / 2
census_pd["Household Income 20,000 to 29,999"] = (census_pd["Household Income 20,000 to 24,999"] + census_pd["Household Income 25,000 to 29,999"]) / 2
census_pd["Household Income 30,000 to 39,999"] = (census_pd["Household Income 30,000 to 34,999"] + census_pd["Household Income 35,000 to 39,999"]) / 2
census_pd["Household Income 40,000 to 49,999"] = (census_pd["Household Income 40,000 to 44,999"] + census_pd["Household Income 45,000 to 49,999"]) / 2

# Configure the final DataFrame
census_pd = census_pd[
    [
        "Name",
        "Household Income Total",
        "Household Income Less than 10,000",
        "Household Income 10,000 to 19,999",
        "Household Income 20,000 to 29,999",
        "Household Income 30,000 to 39,999",
        "Household Income 40,000 to 49,999",
        "Household Income 50,000 to 59,999",
        "Household Income 60,000 to 74,999",
        "Household Income 75,000 to 99,999",
        "Household Income 100,000 to 124,999",
        "Household Income 125,000 to 149,999",
        "Household Income 150,000 to 199,999",
        "Household Income 200,000 or more"
    ]
]

# Display DataFrame length and sample data
print(f"Number of rows in the DataFrame: {len(census_pd)}")
census_pd

Number of rows in the DataFrame: 52

,Name,Household Income Total,"Household Income Less than 10,000","Household Income 10,000 to 19,999","Household Income 20,000 to 29,999","Household Income 30,000 to 39,999","Household Income 40,000 to 49,999","Household Income 50,000 to 59,999","Household Income 60,000 to 74,999","Household Income 75,000 to 99,999","Household Income 100,000 to 124,999","Household Income 125,000 to 149,999","Household Income 150,000 to 199,999","Household Income 200,000 or more"
0,Alabama,1902983.0,140205.0,101830.5,96219.5,90035.0,80069.0,146226.0,182306.0,230067.0,158503.0,104753.0,106617.0,97998.0
1,Alaska,260561.0,10644.0,7956.5,7643.0,8604.0,8311.5,18272.0,27653.0,35821.0,28393.0,21629.0,26172.0,26947.0
2,Arizona,2683557.0,148295.0,94366.5,110989.0,113804.5,112648.0,213802.0,274373.0,361450.0,259428.0,176969.0,186606.0,199018.0
3,Arkansas,1158460.0,79251.0,62938.5,65154.0,59728.0,51927.5,94126.0,115224.0,137297.0,91658.0,54051.0,54652.0,52705.0
4,California,13217586.0,608329.0,433807.0,433019.5,432160.0,410147.5,817962.0,1129455.0,1621793.0,1309828.0,1000924.0,1314071.0,1996956.0
5,Colorado,2227932.0,97533.0,63191.5,70253.0,75431.5,77355.5,158600.0,216060.0,298937.0,239941.0,178942.0,217388.0,248068.0
6,Connecticut,1397324.0,66533.0,45658.0,46146.0,44952.5,44444.5,88807.0,119766.0,169273.0,138944.0,107526.0,140910.0,203163.0
7,Delaware,381097.0,18656.0,12074.0,13868.0,15552.5,14107.5,27844.0,38161.0,53499.0,37888.0,28828.0,32528.0,32489.0
8,District of Columbia,310104.0,25716.0,9991.0,7244.0,7995.5,7331.0,15817.0,22151.0,35005.0,27053.0,22223.0,31658.0,65358.0
9,Florida,8157420.0,479790.0,327215.0,371411.5,371638.5,350725.0,657396.0,825031.0,1045393.0,728826.0,470060.0,513107.0,595837.0
10,Georgia,3885371.0,235927.0,155109.5,168192.0,164864.0,150890.0,290406.0,385679.0,500145.0,355143.0,248254.0,275916.0,315790.0
11,Hawaii,478413.0,22771.0,11798.5,13054.0,14735.0,14904.0,28406.0,43501.0,65498.0,53986.0,40256.0,53902.0,61110.0
12,Idaho,657101.0,28187.0,25223.0,28360.0,29602.0,28856.0,57359.0,76548.0,90429.0,65644.0,38814.0,38881.0,37157.0
13,Illinois,4930255.0,289764.0,173857.0,190793.5,183030.5,175666.5,339016.0,462671.0,634032.0,491848.0,349265.0,418667.0,498297.0
14,Indiana,2622601.0,145585.0,104465.5,118796.5,121609.0,112103.0,215363.0,277437.0,362436.0,249847.0,159424.0,157816.0,140745.0
15,Iowa,1275893.0,59741.0,50220.0,52663.5,55186.0,53527.5,104349.0,135773.0,181264.0,132691.0,83649.0,81830.0,73402.0
16,Kansas,1139738.0,56498.0,42425.5,50463.0,49229.0,49646.5,91904.0,118637.0,155373.0,109764.0,72494.0,76839.0,74701.0
17,Kentucky,1748475.0,130824.0,88283.0,87386.5,82313.5,74745.5,136297.0,175317.0,218767.0,150697.0,95197.0,90904.0,85015.0
18,Louisiana,1748688.0,151146.0,98648.0,91329.5,79143.5,68333.0,126078.0,156220.0,198838.0,143870.0,96281.0,102229.0,99118.0
19,Maine,571064.0,28613.0,25535.5,25381.5,25286.5,23430.5,44126.0,57818.0,79889.0,54723.0,35624.0,37807.0,33196.0
20,Maryland,2294270.0,104364.0,58584.0,62143.5,66522.5,68612.5,140344.0,196437.0,289593.0,250383.0,194076.0,263465.0,343883.0
21,Massachusetts,2714448.0,129130.0,98510.0,83785.5,80121.0,76190.5,152326.0,213588.0,316270.0,267817.0,215561.0,300065.0,442477.0
22,Michigan,3976729.0,234431.0,158983.5,174651.5,178611.5,165459.0,310900.0,400974.0,526260.0,369813.0,248749.0,266048.0,264143.0
23,Minnesota,2229100.0,86754.0,69865.0,74429.5,80007.0,81819.5,159459.0,218727.0,311870.0,242477.0,178637.0,203105.0,215829.0
24,Mississippi,1108670.0,96864.0,68743.5,62128.0,53305.0,48406.0,84639.0,103326.0,130944.0,84237.0,50851.0,50588.0,42056.0
25,Missouri,2433819.0,136741.0,104099.5,111942.5,113016.5,104844.5,194118.0,249881.0,322544.0,222322.0,145771.0,147830.0,146806.0
26,Montana,436481.0,22775.0,18404.5,21390.0,20751.5,18369.0,35826.0,47545.0,57062.0,39990.0,24858.0,26117.0,24478.0
27,Nebraska,766887.0,35439.0,28050.0,31049.5,32816.0,32246.5,61808.0,81857.0,108503.0,79987.0,50586.0,52519.0,47864.0
28,Nevada,1141952.0,67384.0,39125.5,46681.5,49472.5,47257.5,88979.0,118447.0,155803.0,114183.0,72489.0,81718.0,77875.0
29,New Hampshire,540498.0,18333.0,15909.5,17561.5,18264.0,17685.0,35697.0,50391.0,73882.0,61870.0,44265.0,57634.0,59586.0
30,New Jersey,3397156.0,147115.0,103646.5,107836.0,103714.0,97250.5,197644.0,275404.0,410984.0,341188.0,267947.0,369660.0,562320.0
31,New Mexico,797596.0,64161.0,42137.0,40789.5,37223.5,34355.5,62084.0,78979.0,92594.0,65630.0,42932.0,43448.0,38757.0
32,New York,7530150.0,456977.0,309770.5,278732.0,257777.5,246709.0,477356.0,638697.0,887015.0,711313.0,521835.0,676774.0,974205.0
33,North Carolina,4034684.0,235452.0,179925.0,187854.5,187959.0,171685.5,312862.0,399234.0,512372.0,357498.0,237824.0,244476.0,280118.0
34,North Dakota,316542.0,16890.0,11663.0,13117.0,12660.5,12017.0,24847.0,31240.0,43965.0,32804.0,23736.0,22989.0,21156.0
35,Ohio,4754161.0,293381.0,199350.5,212471.5,212748.5,198987.5,372687.0,484104.0,628149.0,444313.0,291036.0,300551.0,292824.0
36,Oklahoma,1503868.0,92674.0,67865.0,78242.0,71491.0,65938.5,125760.0,154893.0,190964.0,132614.0,82464.0,80411.0,77015.0
37,Oregon,1658091.0,84552.0,60672.0,63446.5,66458.0,63317.5,122270.0,167046.0,223511.0,168085.0,114788.0,130812.0,139239.0
38,Pennsylvania,5147783.0,275900.0,207521.5,212898.0,211809.5,195343.5,375745.0,503653.0,679745.0,502626.0,342972.0,380936.0,431061.0
39,Rhode Island,426769.0,21194.0,18430.0,15818.0,15042.0,14711.5,27596.0,37772.0,57528.0,45140.0,33926.0,37039.0,38571.0
40,South Carolina,1976447.0,136273.0,88652.5,93635.5,92725.0,84967.0,156392.0,198401.0,251920.0,168104.0,113602.0,114473.0,117322.0
41,South Dakota,345779.0,16122.0,13404.0,14859.5,16192.5,15051.5,27626.0,36763.0,51170.0,35402.0,22050.0,19680.0,17951.0
42,Tennessee,2664791.0,165651.0,124334.5,124060.0,126616.0,116603.5,211947.0,273378.0,340089.0,235515.0,144914.0,151364.0,158705.0
43,Texas,10239341.0,582804.0,381148.5,422247.5,423141.0,397207.0,764124.0,1003541.0,1297103.0,975061.0,686142.0,787514.0,895564.0
44,Utah,1033651.0,36609.0,26264.5,31416.5,35737.5,38525.0,75298.0,112196.0,156374.0,122817.0,87243.0,90896.0,88331.0
45,Vermont,262514.0,10819.0,11016.0,10834.0,10693.5,10039.0,19586.0,27131.0,36387.0,27173.0,18568.0,18858.0,18827.0
46,Virginia,3248528.0,150800.0,99303.0,110322.0,109563.0,109899.5,221224.0,292323.0,414535.0,328875.0,243458.0,315040.0,424098.0
47,Washington,2931841.0,122237.0,83812.5,91121.5,95320.0,99036.5,200810.0,278463.0,391503.0,316297.0,232045.0,287746.0,364159.0
48,West Virginia,711352.0,55868.0,41651.5,39200.0,35435.5,31037.5,57258.0,68655.0,84207.0,57019.0,34410.0,31940.0,27346.0
49,Wisconsin,2401818.0,101769.0,86589.0,103330.5,98486.0,100519.5,194576.0,256538.0,344384.0,248943.0,164770.0,165972.0,147016.0
50,Wyoming,230653.0,11557.0,8597.5,9463.0,9445.5,8459.5,18169.0,23853.0,33153.0,25943.0,16190.0,16818.0,13039.0
51,Puerto Rico,1196790.0,299201.0,129349.0,89849.0,62444.0,43885.5,65532.0,62174.0,55027.0,25623.0,12994.0,11610.0,13574.0